### PR TITLE
API-12322 Add vaccine code note to Immunization

### PR DESCRIPTION
**Pull request by taylorrassmannlibertyits**
Updated Immunization description to include a Notes section with vaccineCode information.

### CODE REVIEW

**Comment by taylorrassmannlibertyits** [comment]
image

**Comment by taylorrassmannlibertyits** [comment]
Hold off on merge until further documentation update provided.

**Comment by bschofield-va** [comment]
If this is going to be more than day, let's close and re-open when it's ready

**Comment by taylorrassmannlibertyits** [comment]
PR can be closed. See https://vajira.max.gov/browse/API-12322 comments for reference.

**Pull request closed without merging**
