### PR TITLE
API-12334 Immunization manufacturer notes

### PR DESCRIPTION
**Pull request by taylorrassmannlibertyits**
Updated with manufacturer notes.

### CODE REVIEW

**Comment by jblefkove-va** [comment]
Is this related to https://github.com/department-of-veterans-affairs/health-apis-fhir-resources/pull/162 ?

**Comment by taylorrassmannlibertyits** [comment]
> Is this related to #162 ?

This is tangentially related. #162 did not need to be done after talking with Adam. After more discussion with Adam the Notes area still needed to be added for this manufacturer update.

**Comment by taylorrassmannlibertyits** [comment]
Note, wait to merge until https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/860 is completed

**Comment by taylorrassmannlibertyits** [comment]
Update preview:
image

**Pull request merged**
